apiVersion: v2
name: minecraft
description: A Helm chart for Minecraft servers on Kubernetes
type: application
version: 0.1.0
appVersion: "1.20.2"
maintainers:
  - name: Mineclifford Team
keywords:
  - minecraft
  - game
  - server
sources:
  - https://github.com/itzg/docker-minecraft-server
  - https://github.com/itzg/docker-minecraft-bedrock-server
dependencies:
  - name: prometheus
    version: "15.10.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "6.40.3"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled