# Azure-specific values for Minecraft helm chart

javaEdition:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: "mineclifford"
      service.beta.kubernetes.io/azure-pip-name: "minecraft-java-pip"
  
  persistence:
    storageClass: "managed-premium"

bedrockEdition:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: "mineclifford"
      service.beta.kubernetes.io/azure-pip-name: "minecraft-bedrock-pip"
  
  persistence:
    storageClass: "managed-premium"

prometheus:
  server:
    persistentVolume:
      storageClass: "managed-premium"

grafana:
  persistence:
    storageClass: "managed-premium"

ingress:
  className: "azure/application-gateway"
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"