# AWS-specific values for Minecraft helm chart

javaEdition:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
  
  persistence:
    storageClass: "gp2"

bedrockEdition:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "udp"
  
  persistence:
    storageClass: "gp2"

prometheus:
  server:
    persistentVolume:
      storageClass: "gp2"

grafana:
  persistence:
    storageClass: "gp2"

ingress:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip