apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-java
spec:
  template:
    spec:
      containers:
      - name: minecraft-java
        resources:
          requests:
            memory: "$(MEMORY_ALLOCATION)"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock
spec:
  template:
    spec:
      containers:
      - name: minecraft-bedrock
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"
          limits:
            memory: "2Gi"
            cpu: "500m"