apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: mineclifford

commonLabels:
  environment: azure
  provider: azure

patches:
  # Service patches for Azure
  - path: patches/services-azure.yaml
    target:
      kind: Service
  
  # Storage class patches for Azure
  - path: patches/storage-azure.yaml
    target:
      kind: PersistentVolumeClaim

configMapGenerator:
  - name: azure-config
    literals:
      - LOCATION=eastus2
      - CLUSTER_NAME=mineclifford-aks

secretGenerator:
  - name: azure-secrets
    literals:
      - AZURE_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000  # Replace with actual subscription ID

images:
  - name: itzg/minecraft-server
    newTag: latest
  - name: itzg/minecraft-bedrock-server
    newTag: latest
  - name: grafana/grafana
    newTag: latest
  - name: prom/prometheus
    newTag: latest