global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

  # Default labels for all metrics
  external_labels:
    monitor: 'mineclifford-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files to load
rule_files:
  - 'rules/minecraft.rules'
  - 'rules/node.rules'
  - 'rules/service.rules'

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'

  # Minecraft Java Server
  - job_name: 'minecraft-java'
    static_configs:
      - targets: ['minecraft-exporter:9150']
        labels:
          instance: 'minecraft-java'
          type: 'java'
    metrics_path: /metrics
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):.*'
        replacement: '$1'

  # Node Exporter for host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'minecraft-host'
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'docker-metrics'
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker service discovery (for Swarm)
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: label
            values: ["com.mineclifford.service=true"]
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_mineclifford_service]
        target_label: service
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_label_com_mineclifford_type]
        target_label: service_type