apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-java
  labels:
    app: minecraft-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-java
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft-java
    spec:
      containers:
      - name: minecraft-java
        image: itzg/minecraft-server:latest
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"
        - name: MEMORY
          value: "2G"
        - name: DIFFICULTY
          value: "normal"
        - name: MODE
          value: "survival"
        - name: MOTD
          value: "Mineclifford Java Server"
        - name: ALLOW_NETHER
          value: "true"
        - name: ENABLE_COMMAND_BLOCK
          value: "true"
        - name: SPAWN_PROTECTION
          value: "0"
        - name: VIEW_DISTANCE
          value: "10"
        - name: TZ
          value: "America/Sao_Paulo"
        ports:
        - containerPort: 25565
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        volumeMounts:
        - name: minecraft-java-data
          mountPath: /data
      volumes:
      - name: minecraft-java-data
        persistentVolumeClaim:
          claimName: minecraft-java-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-java
spec:
  selector:
    app: minecraft-java
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-java-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard