apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minecraft-java-deployment.yaml
  - minecraft-bedrock-deployment.yaml
  - namespace.yaml
  - volume-claims.yaml
  - monitoring.yaml

commonLabels:
  app: minecraft
  managed-by: mineclifford

commonAnnotations:
  app.kubernetes.io/part-of: mineclifford
  
configMapGenerator:
  - name: minecraft-config
    literals:
      - MINECRAFT_VERSION=latest
      - MINECRAFT_GAMEMODE=survival
      - MINECRAFT_DIFFICULTY=normal
      - MEMORY_ALLOCATION=2G
      - SERVER_NAME=Mineclifford

secretGenerator:
  - name: minecraft-secrets
    literals:
      - RCON_PASSWORD=minecraft
      - GRAFANA_PASSWORD=admin

patchesStrategicMerge:
  - patches/resources-patch.yaml